# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326d8c2aabcc6a7dee05b8f7529f8ea929672e31db52cb1cb1cd97bf6fd3af66f42b43f47e0ff9513fbdd373fbbef30c7b9ace920621072e940bb997824f8e9e

test:
  secret_key_base: b0623802f6f48cc533cc6d7ab5f8adaeda0f0140bed2cddeec85c41472095fe8a1994031a80a32b8fa851ee4c8a7ded69dff02f58ee3a856034addff49abecd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["AAA_SECRET_KEY_BASE"] %>
